sonar.projectKey=olehio-p_InformationSecurity
sonar.organization=olehio-p
sonar.host.url=https://sonarcloud.io

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Standard settings
sonar.java.binaries=target/classes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.junit.reportsPath=target/surefire-reports