name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test
        run: mvn -B verify

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: 75afe332233ca14c6df9ff77c73fb843044378dd
        run: |
          mvn -B sonar:sonar \
            -Dsonar.projectKey=olehio-p_InformationSecurity \
            -Dsonar.organization=olehio-p \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
